--------------------------------------------------------
-- Archivo creado  - lunes-junio-12-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_MENU
--------------------------------------------------------

   CREATE SEQUENCE  "SISUPA_OW"."SEQ_MENU"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PERMISO
--------------------------------------------------------

   CREATE SEQUENCE  "SISUPA_OW"."SEQ_PERMISO"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ROL
--------------------------------------------------------

   CREATE SEQUENCE  "SISUPA_OW"."SEQ_ROL"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "SISUPA_OW"."SEQ_USUARIO"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "SISUPA_OW"."MENU" 
   (	"MNU_ID" NUMBER(*,0), 
	"MNU_PADRE_ID" NUMBER(*,0), 
	"MNU_NOMBRE" VARCHAR2(80 BYTE), 
	"MNU_URL" VARCHAR2(250 BYTE), 
	"MNU_DESCRIPCION" VARCHAR2(4000 BYTE), 
	"FEC_CREA" TIMESTAMP (6), 
	"USU_CREA" VARCHAR2(6 BYTE), 
	"FEC_MODI" TIMESTAMP (6), 
	"USU_MODI" VARCHAR2(6 BYTE), 
	"REG_ACTIVO" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERMISO
--------------------------------------------------------

  CREATE TABLE "SISUPA_OW"."PERMISO" 
   (	"PER_ID" NUMBER(*,0), 
	"PER_ROL_ID" NUMBER(*,0), 
	"PER_MNU_ID" NUMBER(*,0), 
	"PER_NOMBRE" VARCHAR2(80 BYTE), 
	"PER_DESCRIPCION" VARCHAR2(4000 BYTE), 
	"FEC_CREA" TIMESTAMP (6), 
	"USU_CREA" VARCHAR2(6 BYTE), 
	"FEC_MODI" TIMESTAMP (6), 
	"USU_MODI" VARCHAR2(6 BYTE), 
	"REG_ACTIVO" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "SISUPA_OW"."ROL" 
   (	"ROL_ID" NUMBER(*,0), 
	"ROL_NOMBRE" VARCHAR2(80 BYTE), 
	"ROL_DESCRIPCION" VARCHAR2(4000 BYTE), 
	"FEC_CREA" TIMESTAMP (6), 
	"USU_CREA" VARCHAR2(6 BYTE), 
	"FEC_MODI" TIMESTAMP (6), 
	"USU_MODI" VARCHAR2(6 BYTE), 
	"REG_ACTIVO" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SISUPA_OW"."USUARIO" 
   (	"USR_ID" NUMBER(*,0), 
	"USR_ROL_ID" NUMBER(*,0), 
	"USR_CARNET" VARCHAR2(6 BYTE), 
	"USR_NOMBRE" VARCHAR2(80 BYTE), 
	"USR_APELLIDO" VARCHAR2(80 BYTE), 
	"USR_DUI" VARCHAR2(10 BYTE), 
	"USR_NIT" VARCHAR2(17 BYTE), 
	"USR_TELEFONO" VARCHAR2(20 BYTE), 
	"USR_CELULAR" VARCHAR2(20 BYTE), 
	"USR_CORREO_ELECTRONICO" VARCHAR2(100 BYTE), 
	"USR_USUARIO" VARCHAR2(6 BYTE), 
	"USR_CONTRASENIA" VARCHAR2(20 BYTE), 
	"USR_FOTO" VARCHAR2(250 BYTE), 
	"USR_DESCRIPCION" VARCHAR2(4000 BYTE), 
	"FEC_CREA" TIMESTAMP (6), 
	"USU_CREA" VARCHAR2(6 BYTE), 
	"FEC_MODI" TIMESTAMP (6), 
	"USU_MODI" VARCHAR2(6 BYTE), 
	"REG_ACTIVO" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SISUPA_OW.MENU
SET DEFINE OFF;
Insert into SISUPA_OW.MENU (MNU_ID,MNU_PADRE_ID,MNU_NOMBRE,MNU_URL,MNU_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (1,null,'Inicio','inicio.xhtml','Menu de inicio',to_timestamp('08/06/17 10:50:05.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',null,null,1);
Insert into SISUPA_OW.MENU (MNU_ID,MNU_PADRE_ID,MNU_NOMBRE,MNU_URL,MNU_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (2,null,'Tactico','tactico.xhtml','Menu de reportes tacticos',to_timestamp('11/06/17 08:10:05.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',null,null,1);
Insert into SISUPA_OW.MENU (MNU_ID,MNU_PADRE_ID,MNU_NOMBRE,MNU_URL,MNU_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (3,null,'Estrategico','estrategico.xhtml','Menu de reportes estrategicos',to_timestamp('11/06/17 08:10:05.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',null,null,1);
Insert into SISUPA_OW.MENU (MNU_ID,MNU_PADRE_ID,MNU_NOMBRE,MNU_URL,MNU_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (4,2,'Reporte 1','-','-',to_timestamp('11/06/17 08:11:24.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',null,null,1);
Insert into SISUPA_OW.MENU (MNU_ID,MNU_PADRE_ID,MNU_NOMBRE,MNU_URL,MNU_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (5,2,'Reporte 2','-','-',to_timestamp('11/06/17 08:11:24.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',null,null,1);
Insert into SISUPA_OW.MENU (MNU_ID,MNU_PADRE_ID,MNU_NOMBRE,MNU_URL,MNU_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (6,2,'Reporte 3','-','-',to_timestamp('11/06/17 08:11:24.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',null,null,1);
Insert into SISUPA_OW.MENU (MNU_ID,MNU_PADRE_ID,MNU_NOMBRE,MNU_URL,MNU_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (7,3,'Reporte 1','-','-',to_timestamp('11/06/17 08:11:36.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',null,null,1);
REM INSERTING into SISUPA_OW.PERMISO
SET DEFINE OFF;
REM INSERTING into SISUPA_OW.ROL
SET DEFINE OFF;
Insert into SISUPA_OW.ROL (ROL_ID,ROL_NOMBRE,ROL_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (1,'Administrador','Administrador del sistema',to_timestamp('08/06/17 10:29:54.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',null,null,1);
Insert into SISUPA_OW.ROL (ROL_ID,ROL_NOMBRE,ROL_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (23,'Desarrollador','Rol temporal para el desarrollo del sistema',to_timestamp('11/06/17 10:55:04.957000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Jramos',null,null,0);
Insert into SISUPA_OW.ROL (ROL_ID,ROL_NOMBRE,ROL_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (24,'Tactico','Rol utilizado para los usuarios del nivel tactico',to_timestamp('11/06/17 11:04:21.555000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Jramos',null,null,0);
Insert into SISUPA_OW.ROL (ROL_ID,ROL_NOMBRE,ROL_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (25,'Estrategico','Rol utilizado para los usuarios del nivel estrategico',to_timestamp('11/06/17 11:06:15.337000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Jramos',null,null,0);
Insert into SISUPA_OW.ROL (ROL_ID,ROL_NOMBRE,ROL_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (39,'Invitado','Rol utilizado para los invitados del sistema',to_timestamp('12/06/17 01:20:47.736000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Jramos',null,null,1);
REM INSERTING into SISUPA_OW.USUARIO
SET DEFINE OFF;
Insert into SISUPA_OW.USUARIO (USR_ID,USR_ROL_ID,USR_CARNET,USR_NOMBRE,USR_APELLIDO,USR_DUI,USR_NIT,USR_TELEFONO,USR_CELULAR,USR_CORREO_ELECTRONICO,USR_USUARIO,USR_CONTRASENIA,USR_FOTO,USR_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (1,1,'AS1234','Administrador del','Sistema',null,null,null,null,'as1234@cnr.gob.sv','AS1234','AS1234',null,null,to_timestamp('08/06/17 10:43:44.000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Javier',to_timestamp('12/06/17 11:06:09.331000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'JR',1);
Insert into SISUPA_OW.USUARIO (USR_ID,USR_ROL_ID,USR_CARNET,USR_NOMBRE,USR_APELLIDO,USR_DUI,USR_NIT,USR_TELEFONO,USR_CELULAR,USR_CORREO_ELECTRONICO,USR_USUARIO,USR_CONTRASENIA,USR_FOTO,USR_DESCRIPCION,FEC_CREA,USU_CREA,FEC_MODI,USU_MODI,REG_ACTIVO) values (21,23,'RU1200','Javier ','Ramos','04834526-6','0614-240393-101-3',null,'7882-8625','jramos@cnr.gob.sv','ru1200','ru1200',null,'Usuario nuevo',to_timestamp('12/06/17 09:12:35.616000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Jramos',to_timestamp('12/06/17 11:05:50.706000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'JR',1);
--------------------------------------------------------
--  DDL for Index PK_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISUPA_OW"."PK_MENU" ON "SISUPA_OW"."MENU" ("MNU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PERMISO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISUPA_OW"."PK_PERMISO" ON "SISUPA_OW"."PERMISO" ("PER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISUPA_OW"."PK_ROL" ON "SISUPA_OW"."ROL" ("ROL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISUPA_OW"."PK_USUARIO" ON "SISUPA_OW"."USUARIO" ("USR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "SISUPA_OW"."MENU" MODIFY ("MNU_ID" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."MENU" MODIFY ("MNU_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."MENU" MODIFY ("FEC_CREA" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."MENU" MODIFY ("USU_CREA" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."MENU" MODIFY ("REG_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY ("MNU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERMISO
--------------------------------------------------------

  ALTER TABLE "SISUPA_OW"."PERMISO" MODIFY ("PER_ID" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."PERMISO" MODIFY ("PER_ROL_ID" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."PERMISO" MODIFY ("PER_MNU_ID" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."PERMISO" MODIFY ("PER_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."PERMISO" MODIFY ("FEC_CREA" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."PERMISO" MODIFY ("USU_CREA" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."PERMISO" MODIFY ("REG_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."PERMISO" ADD CONSTRAINT "PK_PERMISO" PRIMARY KEY ("PER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "SISUPA_OW"."ROL" MODIFY ("ROL_ID" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."ROL" MODIFY ("ROL_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."ROL" MODIFY ("REG_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."ROL" ADD CONSTRAINT "PK_ROL" PRIMARY KEY ("ROL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("USR_ID" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("USR_ROL_ID" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("USR_CARNET" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("USR_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("USR_APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("USR_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("USR_CONTRASENIA" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("FEC_CREA" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("USU_CREA" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" MODIFY ("REG_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "SISUPA_OW"."USUARIO" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("USR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "SISUPA_OW"."MENU" ADD CONSTRAINT "FK_MNU_MNU_PADRE" FOREIGN KEY ("MNU_PADRE_ID")
	  REFERENCES "SISUPA_OW"."MENU" ("MNU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERMISO
--------------------------------------------------------

  ALTER TABLE "SISUPA_OW"."PERMISO" ADD CONSTRAINT "FK_PER_MNU" FOREIGN KEY ("PER_MNU_ID")
	  REFERENCES "SISUPA_OW"."MENU" ("MNU_ID") ENABLE;
  ALTER TABLE "SISUPA_OW"."PERMISO" ADD CONSTRAINT "FK_PER_ROL" FOREIGN KEY ("PER_ROL_ID")
	  REFERENCES "SISUPA_OW"."ROL" ("ROL_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SISUPA_OW"."USUARIO" ADD CONSTRAINT "FK_USR_ROL" FOREIGN KEY ("USR_ROL_ID")
	  REFERENCES "SISUPA_OW"."ROL" ("ROL_ID") ENABLE;
